/*
 * This source file was generated by the Gradle 'init' task
 */
package com.schoolstudentsystem.console

import org.junit.Assert.assertNotNull
import org.junit.Test

class AppTest {
    @Test
    fun appHasAGreeting() {
        val classUnderTest = App()
        assertNotNull("app should have a greeting", classUnderTest.greeting)
    }
}
